package com.example.notesapp.ui.theme

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color

data class AppColors(
    val primary: Color,
    val secondary: Color,
    val background: Color,
    val surface: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val onPrimary: Color,
    val onSecondary: Color,
    val border: Color,
    val error: Color,
    val divider: Color,
    val accentYellow: Color,
    val accentPink: Color,
    val accentMint: Color,
    val accentBlue: Color,
    val searchBackground: Color,
    val searchIcon: Color,
    val highlight: Color,
    val proBadgeStart: Color,
    val proBadgeEnd: Color,
    val heroBannerStart: Color,
    val heroBannerEnd: Color,
    val settingsBackground: Color,
    val accentGradientStart: Color,
    val accentGradientEnd: Color,
    val avatarBackground: Color,
    val avatarIcon: Color
)

val LightAppColors = AppColors(
    primary = Color(0xFF7C6CF2),
    secondary = Color(0xFF9B8CFF),
    background = Color(0xFFF8F7FF),
    surface = Color(0xFFFFFFFF),
    textPrimary = Color(0xFF191627),
    textSecondary = Color(0xFF7B7694),
    textTertiary = Color(0xFFA0A6AC),
    onPrimary = Color(0xFFFFFFFF),
    onSecondary = Color(0xFFFFFFFF),
    border = Color(0xFFE7E3F6),
    error = Color(0xFFC44A4A),
    divider = Color(0xFFE7EBF0),
    accentYellow = Color(0xFFFFD66B),
    accentPink = Color(0xFFFFBFD7),
    accentMint = Color(0xFFC6F1E7),
    accentBlue = Color(0xFFCFE1FF),
    searchBackground = Color(0xFFEEEFF1),
    searchIcon = Color(0xFF8E959B),
    highlight = Color(0xFFF0F4FF),
    proBadgeStart = Color(0xFF9B8CFF),
    proBadgeEnd = Color(0xFFE06FD8),
    heroBannerStart = Color(0xFF7C6CF2),
    heroBannerEnd = Color(0xFFC569E0),
    settingsBackground = Color(0xFFF8F8FA),
    accentGradientStart = Color(0xFFF3F7FF),
    accentGradientEnd = Color(0xFFEDF3FF),
    avatarBackground = Color(0xFFE8C39D),
    avatarIcon = Color(0xFF2E3640)
)

val DarkAppColors = AppColors(
    primary = Color(0xFF9B8CFF),
    secondary = Color(0xFF7C6CF2),
    background = Color(0xFF121212),
    surface = Color(0xFF1E1E1E),
    textPrimary = Color(0xFFE1E1E1),
    textSecondary = Color(0xFFB0B0B0),
    textTertiary = Color(0xFF808080),
    onPrimary = Color(0xFF121212),
    onSecondary = Color(0xFF121212),
    border = Color(0xFF333333),
    error = Color(0xFFCF6679),
    divider = Color(0xFF2C2C2C),
    accentYellow = Color(0xFFD4AF37),
    accentPink = Color(0xFFD81B60),
    accentMint = Color(0xFF00897B),
    accentBlue = Color(0xFF1976D2),
    searchBackground = Color(0xFF2C2C2C),
    searchIcon = Color(0xFFB0B0B0),
    highlight = Color(0xFF2A2A3A),
    proBadgeStart = Color(0xFF7C6CF2),
    proBadgeEnd = Color(0xFFC569E0),
    heroBannerStart = Color(0xFF5A4EB3),
    heroBannerEnd = Color(0xFF8E4AA3),
    settingsBackground = Color(0xFF121212),
    accentGradientStart = Color(0xFF1A1A2E),
    accentGradientEnd = Color(0xFF16213E),
    avatarBackground = Color(0xFF8D6E63),
    avatarIcon = Color(0xFFE1E1E1)
)

val LocalAppColors = compositionLocalOf { LightAppColors }
